version: '3.9'
services:
  mobile-web:
    build:
      context: ./PictsManager
      dockerfile: Dockerfile
    container_name: server-mobile
    restart: unless-stopped
    environment:
        - BACK_API_URL=http://192.168.1.3:8080/api/
    ports:
      - "${DOCKER_WEB_PORT:-8080}:80"
    volumes:
      - shared-data:/var/www/
      - ./docker/nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/index.html:/var/www/index.html

  server-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: server-api
    restart: unless-stopped
    ports:
      - "${DOCKER_API_PORT:-8081}:80"
    depends_on:
      - mobile-web
      - mongo
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo_user:mongo_password@mongo:27017/my_database
      MONGO_DATABASE_NAME: my_database
  
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "${DOCKER_MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      MONGO_INITDB_DATABASE: my_database

volumes:
    shared-data:
    mongo-data: